# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yvmCDlTSg_cIQtOpfvp3YsaO7U1DIbLC
"""

# pip install -q -U google-generativeai

# pip install ipywidgets

import google.generativeai as genai
import os

# Set your API key
os.environ["KEY"] = "AIzaSyA8arRfdpDVfkDwKPNO4QSnrpEOpOlk__4"
genai.configure(api_key=os.environ["KEY"])

def list_available_models():
    models = genai.list_models()
    for model in models:
        print("====================================================--------------------------")
        print(f"Model Name: {model.name}, \n Description: {getattr(model, 'description', 'No description available')}")
        print("====================================================--------------------------")

# Call the function to list models
# list_available_models()

model = genai.GenerativeModel("models/gemini-pro")

def generate_contet(prompt):
    response = model.generate_content(prompt)
    return response.text

# prompt = input("How may i help Today............")
# content = generate_contet(prompt)

# print("\n\n==================================\n",content)

# prompt = input("How may i help Today............")
# content = generate_contet(prompt)

# print("\n\n==================================\n",content)